import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../components/nav"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import "bootstrap/dist/css/bootstrap.css"
import Footer from "@/components/footer";
import HeroSec from "../components/heroSec"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Nav />
        </header>
        <div>
          <HeroSec />
        </div>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
